name: Init
on:
  push:
jobs:
  init:
    if: ${{ github.repository != 'paralenz/template-ts-package' }}
    name: Init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hello world"