name: Init
on:
  push:
    branches:
      - master
jobs:
  init:
    if: ${{ github.repository != 'paralenz/template-ts-package' }}
    name: Init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Replace name
        run: |
          sed -e 's/%name%/the-name/i' package.json >> package.json
          sed -e 's/%name%/the-name/i' readme.tmpl >> README.md
      - name: Rename workflow files
        run: |
          mv ./github/workflows/_pull-request.tmpl ./github/workflows/pull-request.yml
          mv ./github/workflows/_publish.tmpl ./github/workflows/publish.yml
          mv ./github/dependabot.tmpl ./github/dependabot.yml
      - name: Delete init workflow
        run: rm ./github/workflows/init.yml
      - uses: paralenz/actions/setup-node@v1.1.3
      - name: Install devDependencies
        run: yarn add -D jest ts-node typescript @types/jest @paralenz/eslint-config-typescript-react
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: .
          message: 🎉 Initial commit
      
